### ISSUE TITLE
Bump linux version in _config.sh

### ISSUE THREAD

**Issue by ghost** [solcloud/NiceOS#2]
The current linux version in _config.sh is 5.10.89 while the latest kernel version is 5.15.13.

**Comment by ghost** [comment]
Made #3 fixing the issue.

**Comment by solcloud** [comment]
Hello, currently by default I keep NiceOS on latest longterm which is currently 5.10.91 but of course you are free to change that locally if you want different kernel version and build that version. 
But I am not targeting to be always in sync with latest upstream versions, I am for example on 5.11.X currently on my machines and I also tried new 5.16. But I don't want many commits just bumping linux versions, currently there is already 5.15.14 version and you post 5.15.13 few hours ago so I am closing this for now since linux version are changing too often.
I will probably bump new version every month or so but thanks for checking and creating issue
